name: module-progress
channels:
  - conda-forge
  - defaults
dependencies:
  - python-dotenv
  - prettytable
  - colorama
  - pandas
  - python
  - tqdm
  - pip
  - pip:
      - canvasapi>=2.0.0
      - pick
