name: module_progress_test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python-dotenv
  - prettytable
  - pandas
  - python=
  - tqdm
  - pip
  - pip:
      - canvasapi==0.15.0
      - pick
